### ISSUE TITLE
Investigate on the different ways for us to have an editor

### ISSUE THREAD

**Issue by wilinetan** [dsc-project-mr/mr-fe-external#4]
**Description of feature/enhancement**
Pros and cons of the different ways and existing libraries out there
- Whether we can integrate it into our web app
- How we can store the data/content for the different libraries
- Pros and cons from user and engineering perspectives (During the meeting someone mentioned that the MR team is not tech savvy so maybe can keep in mind they would want something simple to use)

**Comment by ramaven** [comment]
Wei Pin's consolidated research: https://candy-wolfsbane-7f2.notion.site/Mercy-Relief-Text-Editor-Research-92c3b45184014896be74d8faeb8874ea
