### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by wilinetan** [dsc-project-mr/mr-fe-external#6]
**Description of feature/enhancement**
Add the icons that we will be using
- the social media icons are already given in MUI icons package so I think you can focus on creating components for the blue coloured icons since MUI defaults it to black

<img width="395" alt="image_2022-10-27_17-47-46" src="https://user-images.githubusercontent.com/51109678/198863870-ea29ff26-c197-4013-8405-d76fd0256538.png">

**Comment by firwer** [comment]
Completed
